# Generated by Django 5.2.5 on 2025-11-19 22:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cajas',
            fields=[
                ('id_caja', models.AutoField(db_column='Id_caja', primary_key=True, serialize=False)),
                ('saldo_inicial', models.DecimalField(db_column='Saldo_inicial', decimal_places=5, max_digits=12)),
                ('saldo_anterior', models.DecimalField(db_column='Saldo_anterior', decimal_places=5, max_digits=12)),
                ('saldo_actual', models.DecimalField(db_column='Saldo_actual', decimal_places=5, max_digits=12)),
                ('saldo_final', models.DecimalField(db_column='Saldo_final', decimal_places=5, max_digits=12)),
                ('fecha_apertura', models.DateTimeField(blank=True, db_column='Fecha_apertura', null=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, db_column='Fecha_cierre', null=True)),
                ('estado_caja', models.IntegerField(db_column='Estado_caja')),
            ],
            options={
                'db_table': 'cajas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleCompras',
            fields=[
                ('id_detalle_compra', models.AutoField(db_column='Id_detalle_compra', primary_key=True, serialize=False)),
                ('precio_unitario_dtc', models.DecimalField(db_column='Precio_unitario_dtc', decimal_places=5, max_digits=12)),
                ('subtotal_dtc', models.DecimalField(db_column='Subtotal_dtc', decimal_places=5, max_digits=12)),
                ('descuento_dtc', models.DecimalField(db_column='Descuento_dtc', decimal_places=5, max_digits=12)),
                ('total_dtc', models.DecimalField(db_column='Total_dtc', decimal_places=5, max_digits=12)),
                ('fecha_entrega_dtc', models.DateField(db_column='Fecha_entrega_dtc')),
                ('descripcion_dtc', models.CharField(blank=True, db_column='Descripcion_dtc', max_length=445, null=True)),
                ('estado_dtc', models.IntegerField(db_column='Estado_dtc')),
            ],
            options={
                'db_table': 'detalle_compras',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleSolicOc',
            fields=[
                ('id_detalle_solic_oc', models.AutoField(db_column='Id_detalle_solic_OC', primary_key=True, serialize=False)),
                ('cantidad_producto_oc', models.IntegerField(db_column='Cantidad_producto_OC')),
                ('precio_unitario_oc', models.DecimalField(db_column='Precio_unitario_OC', decimal_places=5, max_digits=12)),
                ('sub_total_oc', models.DecimalField(db_column='Sub_total_OC', decimal_places=5, max_digits=12)),
                ('fecha_oc', models.DateField(db_column='Fecha_OC')),
                ('decripcion_oc', models.CharField(db_column='Decripcion_OC', max_length=455)),
                ('estado_oc', models.IntegerField(db_column='Estado_OC')),
            ],
            options={
                'db_table': 'detalle_solic_oc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmpRoles',
            fields=[
                ('id_rol_emp', models.AutoField(db_column='Id_rol_emp', primary_key=True, serialize=False)),
                ('estado_emp_rol', models.IntegerField(blank=True, db_column='Estado_emp_rol', null=True)),
            ],
            options={
                'db_table': 'emp_roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mascotas',
            fields=[
                ('id_mascotas', models.AutoField(db_column='Id_mascotas', primary_key=True, serialize=False)),
                ('estado_mascota', models.IntegerField(blank=True, db_column='Estado_mascota', null=True)),
            ],
            options={
                'db_table': 'mascotas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrdenCompras',
            fields=[
                ('id_orden_compra', models.AutoField(db_column='Id_orden_compra', primary_key=True, serialize=False)),
                ('fecha_emision_orden', models.DateField(db_column='Fecha_emision_orden')),
                ('total_orden', models.DecimalField(db_column='Total_orden', decimal_places=5, max_digits=12)),
                ('estado_orden', models.IntegerField(db_column='Estado_orden')),
            ],
            options={
                'db_table': 'orden_compras',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrecioServicios',
            fields=[
                ('id_precio_servicio', models.AutoField(db_column='Id_precio_servicio', primary_key=True, serialize=False)),
                ('precio_unitario_preser', models.DecimalField(db_column='Precio_unitario_preser', decimal_places=5, max_digits=12)),
                ('precio_completo_preser', models.DecimalField(db_column='Precio_completo_preser', decimal_places=5, max_digits=12)),
                ('descripcion_precio_servicio', models.CharField(blank=True, db_column='Descripcion_precio_servicio', max_length=455, null=True)),
                ('estado_precio_servicio', models.IntegerField(blank=True, db_column='Estado_precio_servicio', null=True)),
            ],
            options={
                'db_table': 'precio_servicios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Provxprod',
            fields=[
                ('id_provxprod', models.AutoField(db_column='Id_provXprod', primary_key=True, serialize=False)),
                ('estado_provxprod', models.IntegerField(blank=True, db_column='Estado_provXprod', null=True)),
                ('nombre_prov', models.CharField(db_column='Nombre_prov', max_length=455)),
                ('nombre_prod', models.CharField(db_column='Nombre_prod', max_length=455)),
                ('fecha_entrega_provxprod', models.DateField(db_column='Fecha_entrega_provXprod')),
                ('descripcion_provxprod', models.CharField(db_column='Descripcion_provXprod', max_length=455)),
            ],
            options={
                'db_table': 'provxprod',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id_rol', models.AutoField(db_column='Id_rol', primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(db_column='Nombre_rol', max_length=95)),
            ],
            options={
                'db_table': 'roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SolicitudOrdenCompras',
            fields=[
                ('id_solicitud_orden_compra', models.AutoField(db_column='Id_solicitud_orden_compra', primary_key=True, serialize=False)),
                ('fecha_solicitud_orc', models.DateField(db_column='Fecha_solicitud_orc')),
                ('descripcion_orc', models.CharField(db_column='Descripcion_orc', max_length=455)),
                ('estado_orc', models.IntegerField(db_column='Estado_orc')),
            ],
            options={
                'db_table': 'solicitud_orden_compras',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id_stock', models.AutoField(db_column='Id_stock', primary_key=True, serialize=False)),
                ('cantidad_stock', models.IntegerField(db_column='Cantidad_stock')),
                ('fecha_egreso_stock', models.DateTimeField(db_column='Fecha_egreso_stock')),
                ('fecha_vencimiento_stock', models.DateTimeField(db_column='Fecha_vencimiento_stock')),
                ('estado_stock', models.IntegerField(db_column='Estado_stock')),
            ],
            options={
                'db_table': 'stocks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CarruselImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, help_text='Título o descripción breve de la imagen.', max_length=100, null=True)),
                ('imagen', models.ImageField(help_text='Sube la imagen para el carrusel.', upload_to='carrusel/')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Número para definir el orden de visualización. Menor número va primero.')),
                ('activo', models.BooleanField(default=True, help_text='Si está activo, se mostrará en el carrusel.')),
                ('fecha_subida', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Imagen del Carrusel',
                'verbose_name_plural': 'Imágenes del Carrusel',
                'db_table': 'carrusel_imagen',
                'ordering': ['orden', '-fecha_subida'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Proveedoress',
            fields=[
                ('id_prov', models.AutoField(db_column='Id_prov', primary_key=True, serialize=False)),
                ('nombre_prov', models.CharField(db_column='Nombre_prov', max_length=45)),
                ('correo_prov', models.CharField(db_column='Correo_prov', max_length=45)),
                ('cuit_prov', models.CharField(db_column='CUIT_prov', max_length=13)),
                ('telefono_prov', models.CharField(db_column='Telefono_prov', max_length=20)),
                ('descripcion_prov', models.CharField(db_column='Descripcion_prov', max_length=455)),
                ('estado_prov', models.IntegerField(blank=True, db_column='Estado_prov', null=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedoress',
                'ordering': ['nombre_prov'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id_servicio', models.AutoField(db_column='Id_servicio', primary_key=True, serialize=False)),
                ('nombre_servicio', models.CharField(db_column='Nombre_servicio', max_length=100)),
                ('tipo_de_servicio', models.CharField(db_column='Tipo_de_servicio', default='Estética', max_length=50)),
                ('descripcion', models.TextField(blank=True, db_column='Descripcion', null=True)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], db_column='Estado', default='Activo', max_length=20)),
            ],
            options={
                'db_table': 'servicios',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Unidades',
            fields=[
                ('id_unidad', models.AutoField(db_column='Id_unidad', primary_key=True, serialize=False)),
                ('unidad_medida', models.CharField(choices=[('litros', 'Litros'), ('gramos', 'Gramos'), ('kilogramos', 'Kilogramos'), ('piezas', 'Piezas')], db_column='Unidad_medida', max_length=20)),
                ('simbolo', models.CharField(choices=[('L', 'L'), ('g', 'g'), ('kg', 'kg'), ('pz', 'pz')], db_column='Simbolo', max_length=5)),
                ('tipo_empaque', models.CharField(choices=[('botella', 'Botella'), ('sachet', 'Sachet'), ('bolsa', 'Bolsa'), ('sobre', 'Sobre'), ('lata', 'Lata'), ('caja', 'Caja'), ('pieza', 'Pieza')], db_column='Tipo_empaque', max_length=30)),
            ],
            options={
                'db_table': 'unidades',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_cliente', models.AutoField(db_column='Id_cliente', primary_key=True, serialize=False)),
                ('nombre_cliente', models.CharField(db_column='Nombre_cliente', max_length=45, validators=[django.core.validators.RegexValidator('^[A-Za-z ]+$', 'Solo letras y espacios.')])),
                ('apellido_cliente', models.CharField(db_column='Apellido_cliente', max_length=45, validators=[django.core.validators.RegexValidator('^[A-Za-z ]+$', 'Solo letras y espacios.')])),
                ('correo_clientes', models.EmailField(db_column='Correo_clientes', max_length=100, unique=True)),
                ('telefono_cliente', models.CharField(blank=True, db_column='Telefono_cliente', max_length=45, null=True)),
                ('dni_cliente', models.CharField(blank=True, db_column='DNI_cliente', max_length=10, null=True, unique=True)),
                ('direccion_cliente', models.CharField(blank=True, db_column='Direccion_cliente', max_length=200, null=True)),
                ('estado_cliente', models.IntegerField(db_column='Estado_cliente', default=1)),
                ('fecha_registro_cliente', models.DateTimeField(auto_now_add=True, db_column='Fecha_registro_cliente')),
                ('foto', models.ImageField(blank=True, db_column='Foto', null=True, upload_to='fotos_cliente/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id_emp', models.AutoField(db_column='Id_emp', primary_key=True, serialize=False)),
                ('sexo_emp', models.CharField(blank=True, db_column='Sexo_emp', max_length=10, null=True)),
                ('nombre_emp', models.CharField(db_column='Nombre_emp', max_length=20, validators=[django.core.validators.RegexValidator('^[A-Za-z ]+$', 'Solo letras y espacios.')])),
                ('apellido_emp', models.CharField(db_column='Apellido_emp', max_length=20, validators=[django.core.validators.RegexValidator('^[A-Za-z ]+$', 'Solo letras y espacios.')])),
                ('dni_emp', models.CharField(db_column='DNI_emp', max_length=8, unique=True)),
                ('direccion', models.CharField(blank=True, db_column='Direccion', max_length=150, null=True)),
                ('telefono', models.CharField(blank=True, db_column='Telefono_emp', max_length=11, null=True)),
                ('email', models.EmailField(blank=True, db_column='Email_emp', max_length=254, null=True)),
                ('cargo', models.CharField(db_column='Cargo', default='sin cargo', max_length=50)),
                ('fecha_ingreso', models.DateField(blank=True, db_column='Fecha_ingreso', null=True)),
                ('sueldo', models.DecimalField(blank=True, db_column='Sueldo', decimal_places=2, max_digits=10, null=True)),
                ('foto', models.ImageField(blank=True, db_column='Foto', null=True, upload_to='fotos_empleados/')),
                ('activo', models.BooleanField(db_column='Activo', default=True)),
                ('force_password_change', models.BooleanField(default=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Empleados',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id_compra', models.AutoField(db_column='Id_compra', primary_key=True, serialize=False)),
                ('nombre_compra', models.CharField(db_column='Nombre_compra', max_length=455)),
                ('cantidad_compra', models.IntegerField(db_column='Cantidad_compra')),
                ('fecha_compra', models.DateField(db_column='Fecha_compra')),
                ('hora_compra', models.TimeField(auto_now_add=True, db_column='Hora_compra', verbose_name='Hora de Compra')),
                ('precio_compra', models.DecimalField(db_column='Precio_compra', decimal_places=5, max_digits=12)),
                ('descripcion_compra', models.CharField(db_column='Descripcion_compra', max_length=455)),
                ('estado_compra', models.IntegerField(blank=True, db_column='Estado_compra', null=True)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta')], db_column='Metodo_pago', default='efectivo', max_length=20, verbose_name='Método de Pago')),
                ('id_caja_fk', models.ForeignKey(db_column='Id_caja_fk', on_delete=django.db.models.deletion.DO_NOTHING, to='app.cajas')),
                ('id_cliente_fk', models.ForeignKey(db_column='Id_cliente_fk', on_delete=django.db.models.deletion.DO_NOTHING, to='app.clientes')),
                ('id_empleado_fk', models.ForeignKey(db_column='Id_empleado_fk', on_delete=django.db.models.deletion.DO_NOTHING, to='app.empleados')),
            ],
            options={
                'db_table': 'compras',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MovimientosCaja',
            fields=[
                ('id_movimiento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_movimiento', models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso')], max_length=10)),
                ('categoria', models.CharField(choices=[('venta', 'Venta'), ('servicios', 'Pago Servicios'), ('otros_ingresos', 'Otros Ingresos'), ('otros_egresos', 'Otros Egresos')], default='otros_ingresos', max_length=30)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('es_automatico', models.BooleanField(default=False)),
                ('estado', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('id_caja_fk', models.ForeignKey(db_column='Id_caja', on_delete=django.db.models.deletion.CASCADE, to='app.cajas')),
                ('id_compra_fk', models.ForeignKey(blank=True, db_column='Id_compra', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.compras')),
                ('id_empleado_fk', models.ForeignKey(db_column='Id_empleado', on_delete=django.db.models.deletion.CASCADE, to='app.empleados')),
            ],
            options={
                'db_table': 'movimientos_caja',
                'ordering': ['-fecha_movimiento'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ServiciosPrestados',
            fields=[
                ('id_serv_prestados', models.AutoField(db_column='Id_serv_prestados', primary_key=True, serialize=False)),
                ('monto_serv', models.DecimalField(blank=True, db_column='Monto_serv', decimal_places=2, max_digits=10, null=True)),
                ('estado', models.CharField(blank=True, choices=[('Pendiente de pago', 'Pendiente de pago'), ('Pagado', 'Pagado'), ('Cancelado', 'Cancelado')], db_column='Estado', default='Pendiente de pago', max_length=20, null=True)),
                ('id_empleados', models.ForeignKey(blank=True, db_column='Id_empleados', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.empleados')),
                ('id_servicio', models.ForeignKey(blank=True, db_column='Id_servicio', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.servicios')),
            ],
            options={
                'db_table': 'servicios_prestados',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Turnos',
            fields=[
                ('id_turno', models.AutoField(db_column='Id_turno', primary_key=True, serialize=False)),
                ('fecha_turno', models.DateField(db_column='Fecha_turno')),
                ('hora_turno', models.TimeField(db_column='Hora_turno')),
                ('motivo_cance_turno', models.CharField(blank=True, db_column='Motivo_cance_turno', max_length=200, null=True)),
                ('estado_turno', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmado', 'Confirmado'), ('En curso', 'En curso'), ('Completado', 'Completado'), ('Cancelado', 'Cancelado'), ('No asistió', 'No asistió')], db_column='Estado_turno', default='Pendiente', max_length=20)),
                ('nombre', models.CharField(db_column='Nombre', default='Sin nombre', max_length=50)),
                ('tipo_turno', models.CharField(db_column='Tipo_turno', default='Perro', max_length=20)),
                ('tamaño_turno', models.CharField(db_column='Tamaño_turno', default='Mediano', max_length=20)),
                ('genero', models.CharField(db_column='Genero', default='Macho', max_length=10)),
                ('edad_turno', models.IntegerField(blank=True, db_column='Edad_turno', null=True)),
                ('observaciones_turno', models.TextField(blank=True, db_column='Observaciones_turno', null=True)),
                ('id_cliente', models.ForeignKey(db_column='Id_cliente', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='app.clientes')),
                ('servicios', models.ManyToManyField(blank=True, through='app.ServiciosPrestados', to='app.servicios')),
            ],
            options={
                'db_table': 'turnos',
                'managed': True,
                'unique_together': {('id_cliente', 'fecha_turno', 'hora_turno')},
            },
        ),
        migrations.AddField(
            model_name='serviciosprestados',
            name='id_turnos',
            field=models.ForeignKey(blank=True, db_column='Id_turno', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.turnos'),
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_prod', models.AutoField(db_column='Id_prod', primary_key=True, serialize=False)),
                ('nombre_prod', models.CharField(db_column='Nombre_prod', max_length=45, validators=[django.core.validators.RegexValidator('^[A-Za-zÁÉÍÓÚáéíóúÑñ0-9 ]+$', 'Solo letras, números, espacios y caracteres especiales.')])),
                ('stock_prod', models.IntegerField(db_column='Stock_prod')),
                ('stock_minimo', models.IntegerField(db_column='Stock_minimo', default=10, help_text='Cantidad mínima de stock antes de mostrar alerta')),
                ('precio_prod', models.DecimalField(db_column='Precio_prod', decimal_places=5, max_digits=12)),
                ('categoria_prod', models.CharField(db_column='Categoria_prod', max_length=45)),
                ('estado_prod', models.IntegerField(blank=True, db_column='Estado_prod', null=True)),
                ('imagen_prod', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('cantidad_unidad', models.DecimalField(blank=True, db_column='Cantidad_unidad', decimal_places=2, max_digits=8, null=True)),
                ('proveedor_prod', models.CharField(blank=True, db_column='Proveedor_prod', max_length=100, null=True)),
                ('eliminado', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('unidad', models.ForeignKey(blank=True, db_column='Id_unidad', null=True, on_delete=django.db.models.deletion.PROTECT, to='app.unidades')),
            ],
            options={
                'db_table': 'productos',
                'managed': True,
            },
        ),
    ]
